class DWP_EventHandler : EventHandler
{
	override void WorldThingDamaged(WorldEvent e)
	{
		if (e.thing)
		{
			//e.thing.Thrust(e.damage * 0.5 * (100 / e.thing.mass), e.damageangle);
		}
		
		Super.WorldThingDamaged(e);
	}
	
	override void WorldThingDied(WorldEvent e)
	{
		bool worlddieddebug = true;
		if (e.thing)
		{
			if (!(e.thing.GetClassName() == "DinahPlayer" || 
			    e.thing.GetClassName() == "ExplosiveBarrel" || 
					e.thing.GetClassName() == "Pod"))
			{
				int user_type;
				string AttackName = "NONE";
				string AttackerName = "NONE";
				if (e.inflictor) AttackName = e.inflictor.GetClassName();
				if (e.inflictor && e.inflictor.target) AttackerName = e.inflictor.target.GetClassName();
				if (worlddieddebug) Console.Printf("\c[purple]Attack: %s, \c[brick]Attacker: %s", AttackName, AttackerName);
				if (e.inflictor && e.inflictor.target && AttackerName == "DinahPlayer") 
				{
					int ExpGain = ((e.thing.spawnhealth()*frandom(0.05,0.125)));
					if (ExpGain < 1) ExpGain = 1;

					e.inflictor.target.A_GiveInventory("KillsCount",1);
					e.inflictor.target.A_GiveInventory("ExpPts",ExpGain);
					int Kills = e.inflictor.target.CountInv("KillsCount"); 
					int ExpNew = e.inflictor.target.CountInv("ExpPts");
					Console.Printf("\c[green]+%d EXP! \c[darkgreen][Have: %d] \c[red](Kills: %d)", ExpGain, ExpNew, Kills);
				}

				// Heal Items
				int maxchance = 256;
				if (AttackName == "BatPuff") maxchance = 128;
				if (AttackName == "BlunderPuff") maxchance = randompick(192,224,256,288,320);
				if (AttackName == "ApplePuff") maxchance = 192;
				if (AttackName == "VacPuff") maxchance = 4096;
				if (random(1,(maxchance)) == 1) e.thing.A_SpawnItemEx("GalaApple",frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),SXF_NOCHECKPOSITION);
				if (random(1,(maxchance)) == 1) e.thing.A_SpawnItemEx("FoodPlateFruit",frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),SXF_NOCHECKPOSITION);
				if (random(1,(maxchance*2)) == 1) e.thing.A_SpawnItemEx("AppleWine",frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),SXF_NOCHECKPOSITION);
				if (random(1,(maxchance*4)) == 1) e.thing.A_SpawnItemEx("PigRoastDishExtra",frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),SXF_NOCHECKPOSITION);
				if (random(1,(maxchance*4)) == 1) e.thing.A_SpawnItemEx("Berserk",frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),SXF_NOCHECKPOSITION);
				
				// Armor Items
				maxchance = 512;
				if (AttackName == "BlunderPuff") maxchance = 8192;
				if (AttackName == "RecordShot") maxchance = 2048;
				if (AttackName == "VacPuff") maxchance = 64;
				if (random(1,maxchance) == 1)
				{
					//Full Armor Drops
					user_type = random(1,100);
					if (user_type >= 1 || user_type <= 67) { e.thing.A_SpawnItemEx("KnightGown",frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),SXF_NOCHECKPOSITION); }
					else if (user_type >= 68 || user_type <= 89) { e.thing.A_SpawnItemEx("KnightGown2",frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),SXF_NOCHECKPOSITION); }
					else if (user_type >= 90) { e.thing.A_SpawnItemEx("KnightGown3",frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),SXF_NOCHECKPOSITION); }
				}
				else
				{
					int scraprolls = 1;
					if (AttackName == "BlunderPuff") scraprolls += randompick(0,0,0,0,1,1,1,1,1,1,2,2,3);
					if (AttackName == "RecordShot") scraprolls += randompick(0,0,0,0,0,0,1,1,1,1,1,2,2);
					if (AttackName == "VacPuff") scraprolls += (randompick(0,0,0,0,0,0,1,1,1,1,1,2,2) - 1);
					//Scrap Drops
					if (scraprolls)
					{
						for (int i = 0; i < scraprolls; i++)
						{
							if (AttackName == "BlunderPuff" && i == 0) e.thing.A_SpawnItemEx("ArmorScrap",frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),SXF_NOCHECKPOSITION);
							if (random(1,3) == 1) e.thing.A_SpawnItemEx("ArmorScrap",frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),SXF_NOCHECKPOSITION);
							if (random(1,9) == 1) e.thing.A_SpawnItemEx("ArmorScrap",frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),SXF_NOCHECKPOSITION);
							if (random(1,27) == 1) e.thing.A_SpawnItemEx("ArmorScrap",frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),SXF_NOCHECKPOSITION);
							if (random(1,81) == 1) e.thing.A_SpawnItemEx("ArmorScrap",frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),SXF_NOCHECKPOSITION);
							if (random(1,243) == 1) e.thing.A_SpawnItemEx("ArmorScrap",frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),SXF_NOCHECKPOSITION);
							if (random(1,729) == 1) e.thing.A_SpawnItemEx("ArmorScrap",frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),frandom(-2,2),SXF_NOCHECKPOSITION);
							if (worlddieddebug) Console.Printf("%d / %d", i, scraprolls);
						}
					}
				}
				
				// Random Inventory Item Drops
				maxchance = 32;
				if (AttackName == "BatPuff") maxchance = 16;
				if (AttackName == "BlunderPuff") maxchance = randompick(24,28,32,36,40);
				if (AttackName == "RecordShot") maxchance = (randompick(24,28,32,36,40) * 2);
				if (AttackName == "VacPuff") maxchance = 512;
				if (random(1,maxchance) == 1)
				{
					user_type = random(1,20);
					if (user_type == 1) { e.thing.A_SpawnItemEx("CherryBombPickup",0.0,0.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION); }
					if (user_type == 2) { e.thing.A_SpawnItemEx("CherryBombPickup",0.0,0.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION); }
					if (user_type == 3) { e.thing.A_SpawnItemEx("CherryBombPickup",0.0,0.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION); }
					if (user_type == 4) { e.thing.A_SpawnItemEx("CherryBombPickup",0.0,0.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION); }
					if (user_type == 5) { e.thing.A_SpawnItemEx("CherryBombPickup",0.0,0.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION); }
					if (user_type == 6) { e.thing.A_SpawnItemEx("CherryBombPickup",0.0,0.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION); }
					if (user_type == 7) { e.thing.A_SpawnItemEx("CherryBombPickup",0.0,0.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION); }
					if (user_type == 8) { e.thing.A_SpawnItemEx("SpinnerPickup",0.0,0.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION); }
					if (user_type == 9) { e.thing.A_SpawnItemEx("SpinnerPickup",0.0,0.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION); }
					if (user_type == 10) { e.thing.A_SpawnItemEx("SpinnerPickup",0.0,0.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION); }
					if (user_type == 11) { e.thing.A_SpawnItemEx("SpinnerPickup",0.0,0.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION); }
					if (user_type == 12) { e.thing.A_SpawnItemEx("SpinnerPickup",0.0,0.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION); }
					if (user_type == 13) { e.thing.A_SpawnItemEx("SpinnerPickup",0.0,0.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION); }
					if (user_type == 14) { e.thing.A_SpawnItemEx("BRocketPickup",0.0,0.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION); }
					if (user_type == 15) { e.thing.A_SpawnItemEx("BRocketPickup",0.0,0.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION); }
					if (user_type == 16) { e.thing.A_SpawnItemEx("BRocketPickup",0.0,0.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION); }
					if (user_type == 17) { e.thing.A_SpawnItemEx("BRocketPickup",0.0,0.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION); }
					if (user_type == 18) { e.thing.A_SpawnItemEx("PopperPickup",0.0,0.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION); }
					if (user_type == 19) { e.thing.A_SpawnItemEx("PopperPickup",0.0,0.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION); }
					if (user_type == 20) { e.thing.A_SpawnItemEx("SnakePickup",0.0,0.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION); }
				}
				
				// Killed With Certain Weapons
				if (e.inflictor)
				{
					if (AttackName == "VacPuff")
					{
						int vacgive = e.thing.spawnhealth();
						vacgive *= frandompick(0.6667,0.8334,1.000,1.1667,1.3334);
						vacgive *= 0.5;
						e.inflictor.target.A_GiveInventory("VacAmmoCounter",vacgive);
						Console.Printf("+%d Vaccum Bag Units", vacgive);
					}
				}
			}
		}
		
		Super.WorldThingDied(e);
	}
	
	override void PlayerDied(PlayerEvent e) 
	{
		S_ChangeMusic("GAMOVR", 0, false, true);
		Super.PlayerDied(e);
	}
	
	override void PlayerRespawned(PlayerEvent e) 
	{
		S_ChangeMusic("*", 0, false, true);
		Super.PlayerRespawned(e);
	}
}

class DWP_StaticEventHandler : StaticEventHandler
{
}