//************************
//* ORIGINAL DD MONSTERS *
//************************
//KILLETANTE
class Killetante : DDCreature
{
	default
	{
		//$Category RPMonsters
		Health 160;
		Radius 20;
		Height 64;
		Speed 10;
		PainChance 256;
		MeleeRange 64;
		Mass 100;
		DamageFactor "Fire", 3;
		DamageFactor "Chop", 3;
		DamageFactor "Beats", 3;
		DamageFactor "Bap", 1;
		PainChance "Bap", 256;
		MONSTER;
		+FLOORCLIP
		+NOINFIGHTING
		+NOBLOOD
		SeeSound "dancer/sight";
		PainSound "dancer/pain";
		DeathSound "virtuoso/death";
		ActiveSound "dancer/active";
		Obituary "%o was out-danced by a Killetante.";
		HitObituary "%o was roundhouse-kicked by a Killetante.";
		Tag "Killetante";
		Species "Killetante";
		+DONTHARMCLASS
		+AVOIDHAZARDS
		+JUMPDOWN
	}
	States
	{
		Spawn:
			DANI A 7 A_Look;
			DANI B 5 A_Look;
			DANI C 7 A_Look;
			DANI D 5 A_Look;
			Loop;
		See:
			DANS BBCCDDEE 3 A_Chase;
			DANS B 0 A_SpawnItemEx("Mininote", 0, 0, 25, 0, random(-1, 1), random(-1, 1));
			DANS B 0 A_Jump(192,"dodge");
			Loop;
		Dodge:
			DANS F 0 A_SpawnItemEx("Mininote", 0, 0, 25, 0, random(-1, 1), random(-1, 1));
			DANS FGH 2 A_FastChase;
			DANS I 0 A_SpawnItemEx("Mininote", 0, 0, 25, 0, random(-1, 1), random(-1, 1));
			DANS IJ 2 A_FastChase;
			Goto See;
		Missile:
			DANS F 0 A_Jump(96,"MusicAttk");
			DANS F 0; //ACS_Execute(102,0,0,0,0)
			DANS F 4 A_Facetarget;
			DANS GHI 4 A_Recoil(-2);
			DANS J 0 ThrustThingz (0, 27, 0, 0);
			DANS J 4 ThrustThing (angle*256/360, 18, 0, 0);
			DANS GHIJ 2;
			DANS D 5 A_CustomMeleeAttack (random(10,15), "mallethit", "malletswing", "", 1);
			Goto See;
		MusicAttk:
			DANS F 0; //ACS_Execute(102,0,0,0,0)
			DANS F 4 A_StartSound("dancer/danceattk",CHAN_BODY);
			DANS GHIFGHI 4 A_Recoil(2);
			DANS J 0 ThrustThingz (0, 27, 0, 0);
			DANS J 4 ThrustThing (angle*256/360, 18, 0, 0);
			DANS D 0 A_StartSound("virtuoso/musicfire",CHAN_VOICE);
			DANS D 4 A_SpawnProjectile("MusicBall",40);
			DANS E 4;
			Goto See;
		Melee:
			DANS F 0; //ACS_Execute(102,0,0,0,0)
			DANS FGHIJ 2 A_Facetarget;
			DANS D 5 A_CustomMeleeAttack (random(10,15), "mallethit", "malletswing", "", 1); 
			Goto See;
		Pain:
			DANS K 2 A_FaceTarget;
			DANS L 0 ThrustThingZ (0, 24, 0, 0);
			DANS L 0 ThrustThing (angle*256/360+180, 6, 0, 0);
			DANS L 6 A_Pain;
			DANS K 6; //ACS_Execute(102,0,0,0,0)
			Goto See;
		/*
		Death.Suck:
			DANS K 5 A_StartSound("VacDed",CHAN_BODY);
			DANS K 2 A_RadiusGive("VacAmmo",128,RGF_PLAYERS,4);
			Stop;
		*/
		Death:
			DANS K 3 A_FaceTarget;
			DANS L 0 ThrustThingZ (0, 24, 0, 0);
			DANS L 0 ThrustThing (angle*256/360+180, 6, 0, 0);
			DANS L 5 A_Scream;
			DANS MNOP 3 bright;
			DANS Q 2 bright A_NoBlocking();
			DANS RSTUVWXYZ 2 bright;
			Stop;
	}
}

class KilletanteBuffDEF : PowerProtection
{
	default
	{
		DamageFactor "Normal", 0.4;
		DamageFactor "Melee", 0.025;
		Powerup.Duration -5;
	}
}

class KilletanteBuffATK : PowerDamage
{
	default
	{
		DamageFactor "Normal", 2.5;
		DamageFactor "Melee", 25;
		Powerup.Duration -5;
	}
}

class KilletanteBuffSPD : PowerSpeed
{
	default
	{
		Speed 1.625;
		Powerup.Duration -5;
	}
}

class KilletanteMistress : Killetante
{
	int reactive1;
	int regentimer, regentimermax;
	default
	{
		Health 240;
		Scale 1.0625;
		Speed 15;
		Mass 150;
		MeleeRange 68;
		PainChance 64;
		DamageFactor 0.875;
		DamageFactor "Fire", 2;
		PainChance "Fire", 128;
		DamageFactor "Chop", 2;
		PainChance "Chop", 128;
		DamageFactor "Beats", 1.5;
		PainChance "Beats", 96;
		DamageFactor "Bap", 1;
		PainChance "Bap", 64;
		MONSTER;
		+FLOORCLIP
		+NOINFIGHTING
		+NOBLOOD
		SeeSound "dancer/sight";
		PainSound "dancer/pain";
		DeathSound "virtuoso/death";
		ActiveSound "dancer/active";
		Obituary "%o was out-tango'd by a Killetante Mistress.";
		HitObituary "%o was roundhouse-kicked over the horizon by a Killetante Mistress.";
		Tag "Killetante Mistress";
		Species "Killetante";
		+DONTHARMCLASS
		+AVOIDHAZARDS
		+JUMPDOWN
	}
	
	override void Tick() 
	{
		int inc = 1;
		int maxhealth = Spawnhealth();
		regentimermax = 63;
		if (health < maxhealth)
		{
			if (health <= (maxhealth*(frandom(0.675,0.825)))) inc *= frandom(1.565,2.1);
			if (health <= (maxhealth*(frandom(0.45,0.55)))) inc *= frandom(1.565,2.1);
			if (health <= (maxhealth*(frandom(0.225,0.275)))) inc *= frandom(1.565,2.1);
			if (health <= (maxhealth*(frandom(0.1125,0.1375)))) inc *= frandom(1.565,2.1);

			if (skill == SKILL_VERY_EASY && !bFRIENDLY) inc *= frandom(0.25,0.50);
			if (skill == SKILL_VERY_EASY && bFRIENDLY) inc *= frandom(1.50,1.75);
			if (skill == SKILL_EASY && !bFRIENDLY) inc *= frandom(0.5,0.75);
			if (skill == SKILL_EASY && bFRIENDLY) inc *= frandom(1.25,1.5);
			if (skill == SKILL_HARD && !bFRIENDLY) inc *= frandom(1.25,1.5);
			if (skill == SKILL_HARD && bFRIENDLY) inc *= frandom(0.5,0.75);
			if (skill == SKILL_VERY_HARD && !bFRIENDLY) inc *= frandom(1.50,1.75);
			if (skill == SKILL_VERY_HARD && bFRIENDLY) inc *= frandom(0.25,0.50);
			if (inc < 1) inc = 1;

			if (reactive1)
			{
				regentimermax *= frandom(0.7,0.9);
				inc *= random(5,6);
			}
			regentimer += inc;
			if (regentimer > regentimermax)
			{
				regentimer -= regentimermax;
				health++;
				if (health > maxhealth) health = maxhealth;
			}
		}
		else
		{
			regentimer = random(-5,5);
		}

		if (reactive1)
		{
			A_SetInventory("KilletanteBuffATK",1);
			A_SetInventory("KilletanteBuffDEF",1);
			A_SetInventory("KilletanteBuffSPD",1);
			if (random(1,4) <= 3) reactive1--;
			Console.Printf("Killetante Mistress Buff Timer: %d", reactive1);
		}
		else
		{
			A_SetInventory("KilletanteBuffATK",0);
			A_SetInventory("KilletanteBuffDEF",0);
		}
		
		Super.Tick();
	}
	States
	{
		Spawn:
			DANI A 7 
			{
				A_SetTics(random(5,7));
				A_Look();
			}
			DANI B 5
			{
				A_SetTics(random(3,5));
				A_Look();
			}
			DANI C 7
			{
				A_SetTics(random(5,7));
				A_Look();
			}
			DANI D 5
			{
				A_SetTics(random(3,5));
				A_Look();
			}
			Loop;
		See:
			DANS BBCCDDEE 3 
			{
				A_Chase();
				if (random(1,4) == 1) { A_SpawnItemEx("Mininote2", 0, 0, 25, 0, random(-1, 1), random(-1, 1)); }
			}
			DANS B 0 
			{
				A_SpawnItemEx("Mininote2", 0, 0, 25, 0, random(-1, 1), random(-1, 1));
				if (random(1,8) <= random(5,7)) { return resolvestate("Dodge"); }

				return resolvestate(null);
			}
			Loop;
		Dodge:
			DANS F 0
			{
				A_SpawnItemEx("Mininote2", 0, 0, 25, 0, random(-1, 1), random(-1, 1));
			}
			DANS FFGGH 1
			{
				A_FastChase();
				if (random(1,10) == 1) { A_SpawnItemEx("Mininote2", 0, 0, 25, 0, random(-1, 1), random(-1, 1)); }
			}
			DANS I 0 
			{
				A_SpawnItemEx("Mininote2", 0, 0, 25, 0, random(-1, 1), random(-1, 1));
			}
			DANS HIIJJ 1 
			{
				A_FastChase();
				if (random(1,10) == 1) { A_SpawnItemEx("Mininote2", 0, 0, 25, 0, random(-1, 1), random(-1, 1)); }
			}
			Goto See;
		Missile:
			DANS F 0 A_Jump(96,"MusicAttk");
			DANS F 0; //ACS_Execute(102,0,0,0,0)
			DANS F 4 
			{
				A_SetTics(randompick(2,3,3,3,4));
				A_Facetarget();
			}
			DANS GHI 4 
			{
				A_SetTics(randompick(2,3,3,3,4));
				A_Recoil(frandompick(-1,1.5,-2,-2.5,-3));
			}
			DANS J 4
			{
				A_SetTics(randompick(2,3,3,3,4));
				ThrustThingz (0, randompick(18,27,36), 0, 0);
				ThrustThing (((angle*256/360*frandom(0.75,1.25))), randompick(18,27,36), 0, 0);
			}
			DANS GHIJ 2
			{
				A_SetTics(randompick(1,1,2,3,3));
				A_Facetarget();
			}
			DANS D 4 
			{
				A_SetTics(random(2,4));
				A_CustomMeleeAttack ((random(20,25)*frandom(0.95,1.05)), "mallethit", "malletswing", "", 1);
			}
			Goto See;
		MusicAttk:
			DANS F 0; //ACS_Execute(102,0,0,0,0)
			DANS F 4 
			{
				A_SetTics(randompick(2,3,3,3,4));
				A_StartSound("dancer/danceattk",CHAN_BODY);
			}
			DANS GHIFGHI 4 
			{
				A_SetTics(randompick(2,3,3,3,4));
				A_Recoil(frandompick(-1,1.5,-2,-2.5,-3));
			}
			DANS J 4 
			{
				A_SetTics(randompick(2,3,3,3,4));
				ThrustThingz (0, randompick(18,27,36), 0, 0);
				ThrustThing (((angle*256/360*frandom(0.75,1.25))), randompick(18,27,36), 0, 0);
			}
			DANS D 4 
			{
				A_SetTics(randompick(2,3,3,3,4));
				A_StartSound("virtuoso/musicfire",CHAN_VOICE);
				A_SpawnProjectile("MusicBall2",40);
			}
			DANS E 4
			{
				A_SetTics(randompick(2,3,3,3,4));
			}
			Goto See;
		Melee:
			DANS F 0; //ACS_Execute(102,0,0,0,0)
			DANS FGHIJ 2 
			{
				A_SetTics(randompick(1,1,2,3,3));
				A_Facetarget();
			}
			DANS D 4
			{
				A_SetTics(random(2,4));
				A_CustomMeleeAttack(random(10,15), "mallethit", "malletswing", "", 1); 
			}
			Goto See;
		Pain:
			DANS K 1 A_FaceTarget;
			DANS L 0 
			{
				ThrustThingZ (0, randompick(16,24,32), 0, 0);
				ThrustThing (((angle*256/360)+(180*frandom(0.75,1.25))), randompick(4,6,8), 0, 0);
			}
			DANS L 3 
			{
				A_Pain();
				reactive1 += random(32,38) * randompick(1,1,1,1,1,1,2,2,2,3);
				A_SetTics(randompick(1,2,2,3));
			}
			DANS L 3 
			{
				A_SetTics(randompick(1,2,2,3));
			}
			DANS K 0; //ACS_Execute(102,0,0,0,0)
			DANS KK 3
			{
				A_SetTics(randompick(1,2,2,3));
			}
			Goto See;
			/*
		Death.Suck:
			DANS K 5 A_StartSound("VacDed",CHAN_BODY);
			DANS K 2 A_RadiusGive("VacAmmo",128,RGF_PLAYERS,4);
			Stop;
			*/
		Death:
			DANS K 3 A_FaceTarget;
			DANS L 0 
			{
				ThrustThingZ (0, randompick(16,24,32), 0, 0);
				ThrustThing (((angle*256/360)+(180*frandom(0.75,1.25))), randompick(4,6,8), 0, 0);
			}
			DANS L 5 A_Scream;
			DANS MNOP 3 bright;
			DANS Q 2 bright A_NoBlocking();
			DANS RSTUVWXYZ 2 bright;
			Stop;
	}
}

//*****************
//* Doom specific *
//*****************
class ExplosiveBarrelNew : ExplosiveBarrel replaces ExplosiveBarrel
{
	default
	{
		Tag "Explosive Barrel";
		+PUSHABLE
	}
	States
	{
		Spawn:
			BAR1 AB 6;
			Loop;
		Death:
			BEXP A 5 Bright;
			BEXP B 5 Bright
			{
				A_Scream();
				A_AlertMonsters();
			}
			BEXP C 5 Bright;
			BEXP D 5 Bright A_Explode(128,128,XF_HURTSOURCE, false,0,0, 10,"BulletPuff");
			BEXP E 10 Bright;
			TNT1 A 1050 Bright A_BarrelDestroy;
			TNT1 A 5 A_Respawn;
			Wait;
	}
}

class ZombiemanNew : Zombieman replaces Zombieman
{
	default
	{
		Tag "Zombieman";
		DamageFactor "Fire", 2.0;
		Painchance "Fire", 256;
		DamageFactor "CherryBomb", 1.5;
		Painchance "CherryBomb", 256;
		DamageFactor "Chop", 1.25;
		Painchance "Chop", 250;
	}
}

class ShotgunGuyNew : ShotgunGuy replaces ShotgunGuy
{
	default
	{
		Tag "Shotgun Guy";
		DamageFactor "Fire", 2.0;
		Painchance "Fire", 256;
		DamageFactor "CherryBomb", 1.5;
		Painchance "CherryBomb", 255;
		DamageFactor "Chop", 1.25;
		Painchance "Chop", 213;
	}
}

class ChaingunGuyNew : ChaingunGuy replaces ChaingunGuy
{
	default
	{
		Tag "Chaingun Guy";
		DamageFactor "Fire", 2.0;
		Painchance "Fire", 256;
		DamageFactor "CherryBomb", 1.5;
		Painchance "CherryBomb", 255;
		DamageFactor "Chop", 1.25;
		Painchance "Chop", 213;
	}
}
class WolfensteinSSNew : WolfensteinSS replaces WolfensteinSS
{
	default
	{
		Tag "Schutzstaffel";
		DamageFactor "Fire", 2.0;
		Painchance "Fire", 256;
		DamageFactor "CherryBomb", 1.5;
		Painchance "CherryBomb", 255;
		DamageFactor "Chop", 1.25;
		Painchance "Chop", 213;
	}
}

class DoomImpNew : DoomImp replaces DoomImp
{
	default
	{
		Tag "Imp";
		DamageFactor "Fire", 0.2;
		Painchance "Fire", 40;
		DamageFactor "CherryBomb", 0.6;
		Painchance "CherryBomb", 120;
		DamageFactor "Chop", 1.5;
		Painchance "Chop", 256;
	}
}

class DemonNew : Demon replaces Demon
{
	default
	{
		Tag "Pinky Demon";
		DamageFactor "Fire", 0.75;
		Painchance "Fire", 135;
		DamageFactor "Suck", 0.75;
		Painchance "Suck", 135;
		DamageFactor "CherryBomb", 0.875;
		Painchance "CherryBomb", 157;
		DamageFactor "Chop", 0.875;
		Painchance "Chop", 157;
		DamageFactor "Breakfast", 2.5;
		Painchance "Breakfast", 256;
		DamageFactor "Bonk", 1.125;
		Painchance "Bonk", 202;
		DamageFactor "Cricket", 1.5;
		Painchance "Cricket", 240;
		DamageFactor "Dust", 1.5;
		Painchance "Dust", 240;
	}
}

class SpectreNew : DemonNew replaces Spectre
{
	default
	{
		Tag "Pinky Spectre";
		+SHADOW
		RenderStyle "OptFuzzy";
	}
}

class LostSoulNew : LostSoul replaces LostSoul
{
	default
	{
		Tag "Lost Soul";
		DamageFactor "Fire", 0.334;
		Painchance "Fire", 85;
		DamageFactor "Suck", 15;
		Painchance "Suck", 256;
		DamageFactor "Bonk", 1.25;
		Painchance "Bonk", 256;
		DamageFactor "Cricket", 2.5;
		Painchance "Cricket", 256;
		DamageFactor "Chop", 5;
		Painchance "Chop", 256;
		DamageFactor "Lead", 0.5;
		Painchance "Lead", 128;
		DamageFactor "Dust", 0.25;
		Painchance "Dust", 64;
		DamageFactor "CherryBomb", 0.25;
		Painchance "CherryBomb", 64;
		DamageFactor "BRocket", 0.5;
		Painchance "BRocket", 128;
		DamageFactor "Spinner", 1.25;
		Painchance "Spinner", 256;
		DamageFactor "Popper", 2.5;
		Painchance "Popper", 256;
		//-RETARGEAFTERNSLAM
	}
}

class CacodemonNew : Cacodemon replaces Cacodemon
{
	default
	{
		Tag "Cacodemon";
		MeleeRange 80;
		DamageFactor "Fire", 0.25;
		Painchance "Fire", 32;
		DamageFactor "Breakfast", 5;
		Painchance "Breakfast", 256;
		DamageFactor "Suck", 0.25;
		Painchance "Suck", 32;
		DamageFactor "CherryBomb", 0.5;
		Painchance "CherryBomb", 64;
		DamageFactor "BRocket", 2.5;
		Painchance "BRocket", 40;
		DamageFactor "Spinner", 3.75;
		Painchance "Spinner", 256;
		DamageFactor "Dust", 5;
		Painchance "Dust", 256;
		DamageFactor "Popper", 0.25;
		Painchance "Popper", 32;
	}

	States
	{
		Melee:
		Missile:
			HEAD B 5 A_FaceTarget;
			HEAD C 5 A_FaceTarget;
			HEAD D 5 BRIGHT A_CustomComboAttack("CacodemonBall", 32, 10 * random(1, 6), "caco/melee");
			Goto See;
	}
}

class PainElementalNew : PainElemental replaces PainElemental
{
	default
	{
		Tag "Pain Elemental";
		MeleeRange 80;
		PainChance "Normal", 16;
		DamageFactor "Fire", 0.5;
		Painchance "Fire", 8;
		DamageFactor "Breakfast", 5;
		Painchance "Breakfast", 80;
		DamageFactor "Suck", 7.5;
		Painchance "Suck", 120;
		DamageFactor "BRocket", 2.5;
		Painchance "BRocket", 40;
		DamageFactor "Dust", 5;
		Painchance "Dust", 80;
		//-RETARGEAFTERNSLAM
	}
	
	States
	{
		Melee:
		Missile:
			PAIN D 5 A_FaceTarget;
			PAIN E 5 A_FaceTarget;
			PAIN F 5 BRIGHT A_FaceTarget;
			PAIN F 0 BRIGHT 
			{
				if (CheckMeleeRange()) 
				{ 
					A_CustomMeleeAttack(10*random(1,6),"caco/melee","none","Melee",true);
				}
				else
				{
					A_PainAttack();
				}
			}
			Goto See;
	}
}

class RevenantNew : Revenant replaces Revenant
{
	default
	{
		Tag "Revenant";
	}
}

class ArachnotronNew : Arachnotron replaces Arachnotron
{
	default
	{
		Tag "Arachnotron";
	}
}

class MancubusNew : Fatso replaces Fatso
{
	default
	{
		Tag "Mancubus";
		DamageFactor "Fire", 0.667;
		Painchance "Fire", 53;
		DamageFactor "Suck", 0.5;
		Painchance "Suck", 40;
		DamageFactor "Bonk", 3.75;
		Painchance "Bonk", 256;
		DamageFactor "Cricket", 0.5;
		Painchance "Cricket", 40;
		DamageFactor "Chop", 5;
		Painchance "Chop", 256;
		DamageFactor "Lead", 1.25;
		Painchance "Lead", 100;
		DamageFactor "Dust", 1.5;
		Painchance "Dust", 120;
		DamageFactor "BRocket", 1.5;
		Painchance "BRocket", 256;
		DamageFactor "CherryBomb", 2;
		Painchance "CherryBomb", 160;
		DamageFactor "Spinner", 1.75;
		Painchance "Spinner", 140;
		DamageFactor "Popper", 1.25;
		Painchance "Popper", 100;
	}
}
class HellKnightNew : HellKnight replaces HellKnight
{
	default
	{
		Tag "Hell Knight";
		DamageFactor "Fire", 0.5;
		Painchance "Fire", 25;
		DamageFactor "CherryBomb", 3.75;
		Painchance "CherryBomb", 187;
		DamageFactor "BRocket", 2.5;
		Painchance "BRocket", 125;
		DamageFactor "Spinner", 2.5;
		Painchance "Spinner", 125;
		DamageFactor "Suck", 0.75;
		Painchance "Suck", 37;
	}
}

class BaronOfHellNew : BaronOfHell replaces BaronOfHell
{
	default
	{
		Tag "Baron of Hell";
		DamageFactor "Fire", 0.5;
		Painchance "Fire", 25;
		DamageFactor "CherryBomb", 3.75;
		Painchance "CherryBomb", 187;
		DamageFactor "BRocket", 2.5;
		Painchance "BRocket", 125;
		DamageFactor "Spinner", 2.5;
		Painchance "Spinner", 125;
		DamageFactor "Suck", 0.75;
		Painchance "Suck", 37;
	}
}

class ArchvileNew : Archvile replaces Archvile
{
	default
	{
		Tag "Archvile";
		DamageFactor "Fire", 0.1;
		Painchance "Fire", 1;
		DamageFactor "Suck", 3.75;
		Painchance "Suck", 38;
		DamageFactor "Bonk", 2.5;
		Painchance "Bonk", 25;
		DamageFactor "Cricket", 5;
		Painchance "Cricket", 5;
		DamageFactor "Chop", 5.0;
		Painchance "Chop", 50;
		DamageFactor "Lead", 1.5;
		Painchance "Lead", 15;
		DamageFactor "BRocket", 1.5;
		Painchance "BRocket", 15;
		DamageFactor "CherryBomb", 0.25;
		Painchance "CherryBomb", 2;
		DamageFactor "Spinner", 1.5;
		Painchance "Spinner", 15;
		DamageFactor "Popper", 1.5;
		Painchance "Popper", 15;
	}
}

class CyberdemonNew : Cyberdemon replaces Cyberdemon
{
	default
	{
		Tag "Cyberdemon";
		DamageFactor "BRocket", 10;
		Painchance "BRocket", 200;
		DamageFactor "CherryBomb", 0.5;
		Painchance "CherryBomb", 10;
		DamageFactor "Spinner", 1.25;
		Painchance "Spinner", 25;
		DamageFactor "Popper", 2.5;
		Painchance "Popper", 50;
		DamageFactor "Suck", 0.25;
		Painchance "Suck", 5;
	}
}

class SpiderMasterMindNew : SpiderMasterMind replaces SpiderMasterMind
{
	default
	{
		Tag "Spider Mastermind";
		DamageFactor "BRocket", 10;
		Painchance "BRocket", 256;
		DamageFactor "CherryBomb", 0.5;
		Painchance "CherryBomb", 20;
		DamageFactor "Spinner", 1.25;
		Painchance "Spinner", 50;
		DamageFactor "Popper", 2.5;
		Painchance "Popper", 100;
		DamageFactor "Suck", 0.25;
		Painchance "Suck", 10;
	}
}

//********************
//* Heretic specific *
//********************
class ChickenNew : Chicken replaces Chicken
{
	default
	{
	}
}

class HereticImpNew : HereticImp replaces HereticImp
{
	default
	{
	}
}

class HereticImpLeaderNew : HereticImpLeader replaces HereticImpLeader
{
	default
	{
	}
}

class MummyNew : Mummy replaces Mummy
{
	default
	{
	}
}

class MummyGhostNew : MummyGhost replaces MummyGhost
{
	default
	{
	}
}

class MummyLeaderNew : MummyLeader replaces MummyLeader
{
	default
	{
	}
}

class MummyLeaderGhostNew : MummyLeaderGhost replaces MummyLeaderGhost
{
	default
	{
	}
}

class KnightNew : Knight replaces Knight
{
	default
	{
	}
}

class KnightGhostNew : KnightGhost replaces KnightGhost
{
	default
	{
	}
}

class WizardNew : Wizard replaces Wizard
{
	default
	{
	}
}

class IronLichNew : IronLich replaces IronLich
{
	default
	{
	}
}

class BeastNew : Beast replaces Beast
{
	default
	{
	}
}

class ClinkNew : Clink replaces Clink
{
	default
	{
	}
}

class MinotaurNew : Minotaur replaces Minotaur
{
	default
	{
	}
}

class SnakeNew : Snake replaces Snake
{
	default
	{
	}
}

class Sorcerer1New : Sorcerer1 replaces Sorcerer1
{
	default
	{
	}
}

class Sorcerer2New : Sorcerer2 replaces Sorcerer2
{
	default
	{
	}
}

//******************
//* Hexen specific *
//******************
class PigNew : Pig replaces Pig
{
	default
	{
	}
}

class FireDemonNew : FireDemon replaces FireDemon
{
	default
	{
	}
}

class EttinNew : Ettin replaces Ettin
{
	default
	{
	}
}

class EttinMashNew : EttinMash replaces EttinMash
{
	default
	{
	}
}

class CentaurNew : Centaur replaces Centaur
{
	default
	{
	}
}

class CentaurMashNew : CentaurMash replaces CentaurMash
{
	default
	{
	}
}

class CentaurLeaderNew : CentaurLeader replaces CentaurLeader
{
	default
	{
	}
}

class Demon1New : Demon1 replaces Demon1
{
	default
	{
	}
}
class Demon1MashNew : Demon1Mash replaces Demon1Mash
{
	default
	{
	}
}

class Demon2New : Demon2 replaces Demon2
{
	default
	{
	}
}

class Demon2MashNew : Demon2Mash replaces Demon2Mash
{
	default
	{
	}
}

class IceGuyNew : IceGuy replaces IceGuy
{
	default
	{
	}
}

class SerpentLeaderNew : SerpentLeader replaces SerpentLeader
{
	default
	{
	}
}

class SerpentNew : Serpent replaces Serpent
{
	default
	{
	}
}

class BishopNew : Bishop replaces Bishop
{
	default
	{
	}
}

class WraithNew : Wraith replaces Wraith
{
	default
	{
	}
}

class WraithBuriedNew : WraithBuried replaces WraithBuried
{
	default
	{
	}
}

class DragonNew : Dragon replaces Dragon
{
	default
	{
	}
}

class ClericBossNew : ClericBoss replaces ClericBoss
{
	default
	{
	}
}

class FighterBossNew : FighterBoss replaces FighterBoss
{
	default
	{
	}
}

class MageBossNew : MageBoss replaces MageBoss
{
	default
	{
	}
}

class KoraxNew : Korax replaces Korax
{
	default
	{
	}
}

class MinotaurFriendNew : MinotaurFriend replaces MinotaurFriend
{
	default
	{
	}
}

//*******************
//* Strife specific *
//*******************

class AcolyteNew : Acolyte replaces Acolyte
{
	default
	{
	}
}

class AcolyteTanNew : AcolyteTan replaces AcolyteTan
{
	default
	{
	}
}

class AcolyteRedNew : AcolyteRed replaces AcolyteRed
{
	default
	{
	}
}

class AcolyteRustNew : AcolyteRust replaces AcolyteRust
{
	default
	{
	}
}

class AcolyteGrayNew : AcolyteGray replaces AcolyteGray
{
	default
	{
	}
}

class AcolyteDGreenNew : AcolyteDGreen replaces AcolyteDGreen
{
	default
	{
	}
}

class AcolyteGoldNew : AcolyteGold replaces AcolyteGold
{
	default
	{
	}
}

class AcolyteLGreenNew : AcolyteLGreen replaces AcolyteLGreen
{
	default
	{
	}
}

class AcolyteBlueNew : AcolyteBlue replaces AcolyteBlue
{
	default
	{
	}
}

class AcolyteShadowNew : AcolyteShadow replaces AcolyteShadow
{
	default
	{
	}
}

class AcolyteToBeNew : AcolyteToBe replaces AcolyteToBe
{
	default
	{
	}
}

class Macil1New : Macil1 replaces Macil1
{
	default
	{
	}
}

class Macil2New : Macil2 replaces Macil2
{
	default
	{
	}
}

class RebelNew : Rebel replaces Rebel
{
	default
	{
	}
}

class Rebel1New : Rebel1 replaces Rebel1
{
	default
	{
	}
}

class Rebel2New : Rebel2 replaces Rebel2
{
	default
	{
	}
}

class Rebel3New : Rebel3 replaces Rebel3
{
	default
	{
	}
}

class Rebel4New : Rebel4 replaces Rebel4
{
	default
	{
	}
}

class Rebel5New : Rebel5 replaces Rebel5
{
	default
	{
	}
}

class Rebel6New : Rebel6 replaces Rebel6
{
	default
	{
	}
}
// TBC :V
